### ISSUE TITLE
TypeError while Linting styled-components with .attr function

### ISSUE THREAD

**Issue by SudharakaP** [brendanmorrell/eslint-plugin-styled-components-a11y#15]
I wonder if this is related to https://github.com/brendanmorrell/eslint-plugin-styled-components-a11y/issues/6 or not but it seems that this package as a bug when used with `styled-components` with `.attr` as shown on the below PR. The linting fails with, 

```
TypeError: Cannot read property 'filter' of undefined
Occurred while linting /home/sudharaka/IdeaProjects/opencollective-frontend/components/StyledLink.js:15
    at TaggedTemplateExpression (/home/sudharaka/IdeaProjects/opencollective-frontend/node_modules/eslint-plugin-styled-components-a11y/lib/utils/collectStyledComponentData.js:99:51)
    at /home/sudharaka/IdeaProjects/opencollective-frontend/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/sudharaka/IdeaProjects/opencollective-frontend/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/sudharaka/IdeaProjects/opencollective-frontend/node_modules/eslint/lib/linter/node-event-generator.js:256:26)
    at NodeEventGenerator.applySelectors (/home/sudharaka/IdeaProjects/opencollective-frontend/node_modules/eslint/lib/linter/node-event-generator.js:285:22)
    at NodeEventGenerator.enterNode (/home/sudharaka/IdeaProjects/opencollective-frontend/node_modules/eslint/lib/linter/node-event-generator.js:299:14)
    at CodePathAnalyzer.enterNode (/home/sudharaka/IdeaProjects/opencollective-frontend/node_modules/eslint/lib/linter/code-path-analysis/code-path-analyzer.js:711:23)
    at /home/sudharaka/IdeaProjects/opencollective-frontend/node_modules/eslint/lib/linter/linter.js:954:32
    at Array.forEach (<anonymous>)
```

For more information and our build please refer to https://github.com/opencollective/opencollective-frontend/pull/5910. And feel free to let me know if you have any questions and I'd be happy to provide any further info. 😄

**Comment by brendanmorrell** [comment]
@SudharakaP. Responded [here](https://github.com/opencollective/opencollective/issues/3980#issuecomment-780949564), but I can take a look at what's going on and get a patch out asap so you can add the plugin to your repo. Thanks for bringing it to my attention!

**Comment by SudharakaP** [comment]
> @SudharakaP. Responded [here](https://github.com/opencollective/opencollective/issues/3980#issuecomment-780949564), but I can take a look at what's going on and get a patch out asap so you can add the plugin to your repo. Thanks for bringing it to my attention!

No problem. Let me know if you need any further clarifications. 👍🏽

**Comment by brendanmorrell** [comment]
@SudharakaP The issue should be fixed now. I just ran eslint on the entire `opencollective/opencollective-frontend` repo with no issues, so if you bump the version to `0.0.32` you should be good to go.
